name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image for test
      run: docker build ./client --file ./client/Dockerfile.dev --tag lokendrachhetri9/react-test
    
    - name: Run the tests
      run: docker run -e CI=true lokendrachhetri9/react-test npm test -- --coverage

    - name: Building all images
      run: |
          docker build -t lokendrachhetri9/multi-client ./client
          docker build -t lokendrachhetri9/multi-nginx ./nginx
          docker build -t lokendrachhetri9/multi-server ./server
          docker build -t lokendrachhetri9/multi-worker ./worker

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push images to the docker Hub
      run: |
          docker push lokendrachhetri9/multi-client 
          docker push lokendrachhetri9/multi-nginx
          docker push lokendrachhetri9/multi-server 
          docker push lokendrachhetri9/multi-worker 