name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image for test
      run: docker build ./client --file ./client/Docker.dev --tag lokendrachhetri9/react-test:$(date +%s)
    
    - name: Run the Docker test
      run: docker run lokendrachhetri9/react-test:$(date +%s) npm test
